Разбил проект на модули
Vaginator3000/MapApplication pull request #1
Opened 2022-01-09 07:05 UTC by Vaginator3000

Разбил проект на модули: 
app (presentation), data, domain, models

2022-01-11 12:07 UTC, mist962 requested changes

2022-01-11 12:07 UTC, mist962 commented on app/build.gradle
> -    testImplementation 'junit:junit:4.+'
удали и папки тестов в модулях

2022-01-11 12:07 UTC, mist962 commented on data/build.gradle
> +        minSdk 21
давай повыше сделаем, до версии 27

2022-01-11 12:07 UTC, mist962 commented on data/build.gradle
> +    compileOptions {
добавь пустую строку

2022-01-11 12:07 UTC, mist962 commented on data/build.gradle
> +    kotlinOptions {
добавь пустую строку

2022-01-11 12:07 UTC, mist962 commented on data/build.gradle
> +}
добавь еще 2 либы dataBinding и viewBinding

2022-01-11 12:07 UTC, mist962 commented on models/build.gradle
> +}
те же коментарии что и выше

2022-01-11 12:07 UTC, mist962 commented on models/src/main/AndroidManifest.xml
> +</manifest>
достаточно 1 строку оставить <manifest package="com.template.models" />

2022-01-11 12:07 UTC, mist962 commented on domain/src/main/AndroidManifest.xml
> +</manifest>
1 строка

2022-01-11 12:07 UTC, mist962 commented on domain/build.gradle
> +}
правки выше

2022-01-11 12:07 UTC, mist962 commented on data/src/main/AndroidManifest.xml
> +</manifest>
1 строка

2022-01-13 07:21 UTC, mist962 requested changes

2022-01-13 07:21 UTC, mist962 commented on app/src/main/java/com/template/mapapplication/ui/places/PlacesViewModel.kt
>          value = "This is dashboard Fragment"
так мы писать не будем, приват юзать так не будем, пиши чисто val text = MutableLiveData("This is dashboard Fragment")

2022-01-13 07:21 UTC, mist962 commented on data/build.gradle
> +    }
зачем тебе в модуле data биндинги ? ты верстать будешь что-то ?

2022-01-13 07:21 UTC, mist962 commented on domain/build.gradle
> +    }
домеин, что тут верстать

2022-01-13 07:21 UTC, mist962 commented on domain/build.gradle
> +    implementation 'com.google.android.material:material:1.4.0'
зачем тебе в домейне материал ?

2022-01-13 07:21 UTC, mist962 commented on models/build.gradle
> +    }
?

2022-01-13 07:21 UTC, mist962 commented on models/build.gradle
> +    implementation 'com.google.android.material:material:1.4.0'
?

2022-01-18 09:00 UTC, mist962 requested changes

2022-01-18 09:00 UTC, mist962 commented on data/src/main/AndroidManifest.xml
> +</manifest>
<manifest package="com.template.data"/>

2022-01-18 09:31 UTC, Vaginator3000 commented on data/build.gradle
> +    compileOptions {
исправил

2022-01-18 09:31 UTC, Vaginator3000 commented on data/build.gradle
> +    kotlinOptions {
есть

2022-01-18 10:20 UTC, Vaginator3000 commented on models/src/main/AndroidManifest.xml
> +</manifest>
исправил

2022-01-18 10:20 UTC, Vaginator3000 commented on domain/src/main/AndroidManifest.xml
> +</manifest>
исправил

2022-01-18 10:21 UTC, Vaginator3000 commented on app/src/main/java/com/template/mapapplication/ui/map/MapFragment.kt
> +    private var _binding: FragmentMapBinding? = null
исправил

2022-01-18 10:21 UTC, Vaginator3000 commented on app/src/main/java/com/template/mapapplication/ui/map/MapFragment.kt
>          val textView: TextView = binding.textHome
исправил

2022-01-19 15:34 UTC, mist962 requested changes

2022-01-21 06:36 UTC, Vaginator3000 commented on app/src/main/java/com/template/mapapplication/ui/map/MapFragment.kt
> +    override fun onCreateView(
Сделал

2022-01-21 06:36 UTC, Vaginator3000 commented on app/src/main/java/com/template/mapapplication/ui/places/PlacesFragment.kt
> +    override fun onCreateView(
Сделал

2022-01-24 07:59 UTC, mist962 requested changes

2022-01-24 07:59 UTC, mist962 commented on app/src/main/java/com/template/mapapplication/ui/map/MapFragment.kt
> +    override fun onCreateView(
Удали этот метод вообще

2022-01-24 07:59 UTC, mist962 commented on app/src/main/java/com/template/mapapplication/ui/places/PlacesFragment.kt
> +    override fun onCreateView(
Удали этот метод

2022-01-24 07:59 UTC, mist962 commented on data/src/main/AndroidManifest.xml
> +<?xml version="1.0" encoding="utf-8"?>
удли эту строчку

2022-01-24 07:59 UTC, mist962 commented on domain/src/main/AndroidManifest.xml
> +<?xml version="1.0" encoding="utf-8"?>
удали эту строчку

2022-01-24 07:59 UTC, mist962 commented on data/src/main/AndroidManifest.xml
> +<manifest package="com.template.data"> </manifest>
> </manifest> поменяй на />

2022-01-24 07:59 UTC, mist962 commented on models/src/main/AndroidManifest.xml
> +<?xml version="1.0" encoding="utf-8"?>
удали

2022-01-24 07:59 UTC, mist962 commented on models/src/main/AndroidManifest.xml
> +<manifest package="com.template.models"> </manifest>
> </manifest> поменяй на />

2022-01-27 12:18 UTC, mist962 approved these changes

2022-01-27 19:04 UTC, merged