login code & make loginFragment as first loading fragment
Vaginator3000/MapApplication pull request #10
Opened 2022-02-15 07:09 UTC by Vaginator3000

- authenticate and login proceses code to loginFragment and loginViewModel
- checks for empty fields 
- make loginFragment as first 
also:
- remove padding in mainActivity
- remove wrong sting
- replace binding in mainActivity to viewBindingDelegate

2022-02-21 13:02 UTC, mist962 requested changes

2022-02-21 13:02 UTC, mist962 commented on app/src/main/java/com/template/mapapplication/ui/login/LoginFragment.kt
> +                val password = (passwordEditText.text ?: return@setOnClickListener).toString()
нет, ты не можешь возвращать так, это будет что попало, убирай return@setOnClickListener

2022-02-22 09:06 UTC, Vaginator3000 commented on app/src/main/java/com/template/mapapplication/ui/login/LoginFragment.kt
> +                val password = (passwordEditText.text ?: return@setOnClickListener).toString()
done

2022-02-22 09:06 UTC, Vaginator3000 commented on app/src/main/java/com/template/mapapplication/ui/login/LoginFragment.kt
> +                } else
done

2022-02-22 09:06 UTC, Vaginator3000 commented on app/src/main/java/com/template/mapapplication/ui/login/LoginFragment.kt
> +                val pass1 = (pass1EditText.text ?: return@setOnClickListener).toString()
done

2022-02-25 08:12 UTC, mist962 approved these changes

2022-02-25 08:48 UTC, merged