add code to tracking places with Retrofit
Vaginator3000/MapApplication pull request #18
Opened 2022-03-02 11:20 UTC by Vaginator3000

- import Retrofit2 with OkHttp
- add GeoResponse model (use Yandex geocode)
- add GeocodeRepository interface id domain with impl in data
- add Retrofit builder
- add TrackingHelper class

2022-03-02 11:36 UTC, mist962 requested changes

2022-03-02 11:36 UTC, mist962 commented on app/src/main/java/com/template/mapapplication/ui/map/MapFragment.kt
> +        //userLocationLayer.isHeadingEnabled = true
закоменченный код не заливаем

2022-03-02 11:36 UTC, mist962 commented on app/src/main/java/com/template/mapapplication/ui/map/MapFragment.kt
> +        userLocationView.accuracyCircle.fillColor = Color.BLUE and -0x66000001
цвет вынеси в константы

2022-03-02 11:36 UTC, mist962 commented on app/src/main/java/com/template/mapapplication/ui/map/MapFragment.kt
> +                PointF((mapview.width * 0.5).toFloat(), (mapview.height * 0.83).toFloat() )
значения в константы

2022-03-02 11:36 UTC, mist962 commented on app/src/main/java/com/template/mapapplication/ui/map/MapFragment.kt
> +    override fun onObjectUpdated(p0: UserLocationView, p1: ObjectEvent) {
просто = Unit место { }

2022-03-02 11:36 UTC, mist962 commented on app/src/main/java/com/template/mapapplication/ui/map/PlacesTrakingHelper.kt
> +            val geocode = "${currentLocation!!.position.longitude}, ${currentLocation!!.position.latitude}"
!! приводит к NPE не используем

2022-03-02 11:36 UTC, mist962 commented on app/src/main/java/com/template/mapapplication/ui/map/PlacesTrakingHelper.kt
> +            this
добавь named Args

2022-03-02 13:13 UTC, Vaginator3000 commented on app/src/main/java/com/template/mapapplication/ui/map/MapFragment.kt
> +        //userLocationLayer.isHeadingEnabled = true
done

2022-03-02 13:13 UTC, Vaginator3000 commented on app/src/main/java/com/template/mapapplication/ui/map/MapFragment.kt
> +        userLocationView.accuracyCircle.fillColor = Color.BLUE and -0x66000001
done

2022-03-02 13:13 UTC, Vaginator3000 commented on app/src/main/java/com/template/mapapplication/ui/map/MapFragment.kt
> +                PointF((mapview.width * 0.5).toFloat(), (mapview.height * 0.83).toFloat() )
fix

2022-03-02 13:13 UTC, Vaginator3000 commented on app/src/main/java/com/template/mapapplication/ui/map/MapFragment.kt
> +    override fun onObjectUpdated(p0: UserLocationView, p1: ObjectEvent) {
+

2022-03-02 13:13 UTC, Vaginator3000 commented on app/src/main/java/com/template/mapapplication/ui/map/PlacesTrakingHelper.kt
> +            this
done

2022-03-05 11:07 UTC, mist962 approved these changes

2022-03-07 07:08 UTC, merged