add login screen xml with string resources
Vaginator3000/MapApplication pull request #7
Opened 2022-02-04 06:09 UTC by Vaginator3000

add login screen xml with string resources and 2 functions to logIn mode and authentiaction mode

2022-02-04 07:52 UTC, Vaginator3000 commented
![image](https://user-images.githubusercontent.com/47788443/152491817-2282785a-c45c-408f-8c4d-b10b11cbc848.png)
![image](https://user-images.githubusercontent.com/47788443/152491843-a2a342db-150c-4bae-a760-a10c64338d6a.png)

2022-02-07 10:24 UTC, mist962 requested changes

2022-02-07 10:24 UTC, mist962 commented on app/src/main/java/com/template/mapapplication/ui/login/LoginFragment.kt
> +            registrationGroup.visibility = View.GONE
не используем View, используем котлин экстеншенс isVisible = true/false

2022-02-07 10:24 UTC, mist962 commented on app/src/main/res/layout/fragment_login.xml
> +
empty line

2022-02-07 10:24 UTC, mist962 commented on app/src/main/res/layout/fragment_login.xml
> +
2 пустые строки

2022-02-07 10:24 UTC, mist962 commented on app/src/main/res/layout/fragment_login.xml
> +
1 пустая

2022-02-07 10:24 UTC, mist962 commented on app/src/main/res/layout/fragment_login.xml
пустая строка

2022-02-11 08:06 UTC, Vaginator3000 commented on app/src/main/res/layout/fragment_login.xml
> +
done

2022-02-11 08:06 UTC, Vaginator3000 commented on app/src/main/res/layout/fragment_login.xml
> +
done

2022-02-11 08:07 UTC, Vaginator3000 commented on app/src/main/res/layout/fragment_login.xml
> +
done

2022-02-14 06:44 UTC, mist962 approved these changes

2022-02-14 18:26 UTC, merged